# These are supported funding model platforms

custom: Dona con PayPal: https://www.paypal.com/donate/?hosted_button_id=YPLH6NHKF7KQ8
patreon: emmecilab
custom: https://www.buymeacoffee.com/emmecilab
